### ISSUE TITLE
Mouse wheel zoom not working without the shiftkey

### ISSUE THREAD

**Issue by gabrielpgava** [Nicolapps/mapkit-react#22]
In the mapkit js has a funcion who makes possible to zoom using the mouse wheel, if we press the shift or ctrl key, so i ask if its possible to make the zoom enable by default, without the need of pressing other keys, maybe it can be fix by overriding the _handleWheelEvent.
Thanks

**Comment by Nicolapps** [comment]
Thanks for the feedback! It seems that MapKit JS has an [undocumented API](https://madebymist.com/text/apple-mapkit-js-how-to-enable-zoom-on-scroll) to do this.

I’ve just released mapkit-react 1.4.0, that adds a new `allowWheelToZoom` property  (efd67d5718739797f552e6ac43af059d823000d9). It is disabled by default, since changing the default behavior would break websites that use maps inside of a scroll area, but you can opt in in your projects.

We just have to keep in mind that since this relies on Apple’s undocumented API, it might break one day. But it seems that some websites such as DuckDuckGo are already using the private API. I sent a feature request for a public API to Apple (FB12019011).
