### ISSUE TITLE
Map does not show up

### ISSUE THREAD

**Issue by jmdapozzo** [Nicolapps/mapkit-react#32]
Sorry for this might seem as a trivial question but I cannot get mapkit-react to show a proper map.
Token is valid and has been tested on the storybook page.
React is version 18.2.0.
My map page is just a simple Map tag with a proper token.

No special warniing when looking at the Chrome console apart from the following two warnings:

vTools failed to load source map: Could not load content for chrome-extension://lmbopdiikkamfphhgcckcjhojnokgfeo/src/tierces_parties/browser-polyfill.min.js.map: System error: net::ERR_BLOCKED_BY_CLIENT

vTools failed to load source map: Could not load content for https://mw-ci1-mapkitjs.geo.apple.com/admin/source-maps/5.75.95/source-maps/mapkit.min.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED

**Comment by Nicolapps** [comment]
Hello, thank you for your message! The first warning seems to be caused by the [Antidote Chrome extension](https://chrome.google.com/webstore/detail/connecteur-antidote/lmbopdiikkamfphhgcckcjhojnokgfeo), but I don’t think that it is related to the issue you’re experiencing. The second warning is normal, it seems to appear in every project that uses MapKit JS.

The map will have the same height as its parent element. If the parent element has no height (e.g. it is an unstyled div), the map will also have zero height and will not appear on the screen. Could that be the origin of your problem?

**Comment by jmdapozzo** [comment]
Hi Nicolas,
I did try to set the height on the Map tag but that did not solve the problem.
You are absolutely right about the height of the containing div. This did solve the problem.

Thanks,
Jean-Marc
