### ISSUE TITLE
Feature Request: Change Color Scheme based on users preferred color scheme

### ISSUE THREAD

**Issue by nikischin** [Nicolapps/mapkit-react#48]
_Disclaimer: This is not a feature offered natively by MapKit JS_

I noticed, that the color scheme of the map always defaults to the light color scheme. This seems to be a design choice by Apple and is not natively supported by the framework.

However, I was wondering if we could introduce a `ColorScheme.Auto`, to automatically switch to the dark theme based on `@media (prefers-color-scheme: dark)`.

Is this something the library should support or is it something the user should rather implement as a custom functionality?

**Comment by Nicolapps** [comment]
That seems like a nice feature to add! It could be implemented using something like this: https://usehooks-ts.com/react-hook/use-dark-mode

**Comment by nikischin** [comment]
Indeed, I was thinking about the same package. Would you prefer, using the package as a dependency or implement it directly like the package does?

**Comment by Nicolapps** [comment]
Using usehooks-ts as a dependency should work, the bundle size shouldn’t be affected if the loader is correctly set up (i.e. uses tree shaking).

`useDarkMode` is more complicated than what we need because it also supports manually changing the theme, but `useMediaQuery('(prefers-color-scheme: dark)')` should do exactly what we want.

**Comment by nikischin** [comment]
Thank you so much for merging!
